### PR TITLE
Final Cart Display

### PR DESCRIPTION
**Pull request by harjotb03**
Retrieve latest web scraping information and display on the cart extension

### CODE REVIEW

**Review by thushv — COMMENTED** [review]
Wow looks really cool! Don't have any other comments to give :)

**Review by vivvvli — APPROVED** [review]
Not much to say because you did a great job! Compared to the beginning of the project, your code is a lot more organized and easy to read

Also amazing job putting everything together in JavaScript, I know how challenging this was :)

**Comment by aneesaali** [comment]
I like how you were able to implement the remaining budget after the current purchase! quick question: does this new budget update the old budget right away, or only if the items are purchased?

**Comment by harjotb03** [comment]
> I like how you were able to implement the remaining budget after the current purchase! quick question: does this new budget update the old budget right away, or only if the items are purchased?

Thanks Aneesa! And good question but unfortunately due to time constraints I wasn't able to get that part resolved. Ideally, yes it should update the budget and use it forward but this is good to keep in mind for next time.

**Pull request merged**
