### PR TITLE
fixed scraper

### PR DESCRIPTION
**Pull request by vivvvli**

### CODE REVIEW

**Comment by aneesaali** [comment]
looks good! I'm glad you were able to get it to work without generating an artificial cart!

**Review by thushv — COMMENTED** [review]
Nice that you got the scraping to work! Did notice that the category was not scraped and wondering if that's a mistake or not. It will be needed for the pie chart

**Comment by vivvvli** [comment]
@thushv As per our discussion, we need machine learning so we'll come up with a different idea for the graph :)

**Comment by thushv** [comment]
@vivvvli thank you for letting me know!

**Comment by harjotb03** [comment]
Awesome job Vivian! Glad to see our previous issues resolved and now that you're able to scrape the users cart I'll be able to display the information on the extension pop-up.

**Pull request merged**
